#
# This is the Volt runtime.
#
name = "volta.rt"
isTheRT = true
#
# Extra files
#

#
# OS deps
#

# For Linux
[cfg.linux]
libraries = ["pthread", "dl", "rt"]

# For Linux or OSX
[cfg.'(osx || linux) && !aarch64']
asmFiles = ["src/vrt/gc/save_regs.asm", "src/vrt/os/eh.asm"]

# AArch has its own special assembly.
[cfg.aarch64]
sFiles = ["src/vrt/aarch64.s"]

# For all Windows builds.
[cfg.msvc]
libraries = ["AdvAPI32.Lib"]
asmFiles = ["src/vrt/gc/save_regs.asm"]

# Old depericated
[platform.linux]
libraries = ["pthread", "dl", "rt"]
[platform.'osx || linux']
asmFiles = ["src/vrt/gc/save_regs.asm", "src/vrt/os/eh.asm"]
[platform.msvc]
libraries = ["AdvAPI32.Lib"]
asmFiles = ["src/vrt/gc/save_regs.asm"]
